FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN test -n "$DATABASE_URL" || (echo "DATABASE_URL is missing during image build" && exit 1)


RUN yarn build

ENV NODE_ENV=production

CMD ["yarn", "start:prod"]