
services:
  # Nest backend application
  developer-profile-api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: developer-profile-api:latest
    container_name: developer-profile-api
    restart: on-failure
    depends_on:
      - app-db
    env_file:
      - ../.env
    ports:
      - "5004:5004"


  # PostgreSQL Database service
  app-db:
    image: postgres:16.4
    volumes:
      - ./volumes/db-data:/var/lib/postgresql/data
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    ports:
      - 5433:5432

    # Adminer for database
  app-adminer:
    image: adminer:latest
    container_name: app-adminer
    links:
      - app-db
    restart: always
    ports:
      - 8082:8080 # port for adminer 8082
    volumes:
      - ./database/adminer.css:/var/www/html/adminer.css # Mount the adminer style

networks:
  default:
    name: app-network
